#!/bin/bash

jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --theme="JupyterLab Dark" > jupyter_log.txt 2>&1 &

sleep 2

LINK=$(grep "http://127.0.0.1:" jupyter_log.txt | head -n 1)

echo "$LINK"

